using FatCat.Domain;

namespace FatCat.Application;

public interface IFatCatRepository
{
    Task<PlayerProfile?> FindPlayerByDeviceIdAsync(string deviceId, CancellationToken cancellationToken);
    Task<PlayerProfile?> FindPlayerByIdAsync(Guid playerId, CancellationToken cancellationToken);
    Task<List<PlayerProfile>> FindPlayersByIdsAsync(IReadOnlyCollection<Guid> playerIds, CancellationToken cancellationToken);
    Task AddPlayerAsync(PlayerProfile player, CancellationToken cancellationToken);
    Task SaveSnapshotAsync(PlayerSaveSnapshot snapshot, CancellationToken cancellationToken);
    Task<PlayerSaveSnapshot?> GetLatestSnapshotAsync(Guid playerId, CancellationToken cancellationToken);
    Task<List<PlayerMail>> GetMailsAsync(Guid playerId, CancellationToken cancellationToken);
    Task<PlayerMail?> GetMailAsync(Guid playerId, string mailKey, CancellationToken cancellationToken);
    Task AddMailAsync(PlayerMail mail, CancellationToken cancellationToken);
    Task<List<FriendSnapshot>> GetFriendsAsync(Guid playerId, CancellationToken cancellationToken);
    Task<FriendSnapshot?> GetFriendAsync(Guid playerId, string friendKey, CancellationToken cancellationToken);
    Task AddFriendAsync(FriendSnapshot friend, CancellationToken cancellationToken);
    Task AddFriendIfMissingAsync(FriendSnapshot friend, CancellationToken cancellationToken);
    Task<PlayerInviteCode?> GetInviteCodeByPlayerIdAsync(Guid playerId, CancellationToken cancellationToken);
    Task<PlayerInviteCode?> GetInviteCodeByCodeAsync(string code, CancellationToken cancellationToken);
    Task AddInviteCodeAsync(PlayerInviteCode inviteCode, CancellationToken cancellationToken);
    Task<PlayerFriendRelation?> GetFriendRelationAsync(Guid playerId, Guid friendPlayerId, CancellationToken cancellationToken);
    Task AddFriendRelationAsync(PlayerFriendRelation relation, CancellationToken cancellationToken);
    Task<PlayerFriendRequest?> GetFriendRequestAsync(Guid requestId, CancellationToken cancellationToken);
    Task<PlayerFriendRequest?> GetFriendRequestBetweenAsync(Guid requesterPlayerId, Guid targetPlayerId, string status, CancellationToken cancellationToken);
    Task<List<PlayerFriendRequest>> GetFriendRequestsAsync(Guid playerId, string box, CancellationToken cancellationToken);
    Task AddFriendRequestAsync(PlayerFriendRequest request, CancellationToken cancellationToken);
    Task AddSocialActivityAsync(PlayerSocialActivity activity, CancellationToken cancellationToken);
    Task<List<PlayerSocialActivity>> GetSocialActivitiesAsync(Guid playerId, int limit, CancellationToken cancellationToken);
    Task AddFriendBoostContributionAsync(PlayerFriendBoostContribution contribution, CancellationToken cancellationToken);
    Task<List<PlayerFriendBoostContribution>> GetFriendBoostContributionsAsync(Guid playerId, int limit, CancellationToken cancellationToken);
    Task ExtendActiveFriendBoostContributionsAsync(Guid playerId, DateTimeOffset now, DateTimeOffset expiresAt, CancellationToken cancellationToken);
    Task<PlayerCoopGoalState?> GetCoopGoalStateAsync(Guid playerId, CancellationToken cancellationToken);
    Task AddCoopGoalStateAsync(PlayerCoopGoalState state, CancellationToken cancellationToken);
    Task<PlayerCoopGoalState> IncrementCoopGoalProgressAsync(Guid playerId, int goalDate, int goalTarget, DateTimeOffset now, CancellationToken cancellationToken);
    Task<bool> ClaimCoopGoalAsync(Guid playerId, int goalDate, int goalTarget, DateTimeOffset now, CancellationToken cancellationToken);
    Task<PlayerSettings?> GetSettingsAsync(Guid playerId, CancellationToken cancellationToken);
    Task SetSettingsAsync(PlayerSettings settings, CancellationToken cancellationToken);
    Task<PlayerResourceState?> GetResourceStateAsync(Guid playerId, CancellationToken cancellationToken);
    Task SetResourceStateAsync(PlayerResourceState state, CancellationToken cancellationToken);
    Task AddResourceTransactionAsync(PlayerResourceTransaction transaction, CancellationToken cancellationToken);
    Task<List<PlayerResourceTransaction>> GetResourceTransactionsAsync(Guid playerId, int limit, CancellationToken cancellationToken);
    Task<PlayerShopPurchaseHistory?> GetShopPurchaseHistoryAsync(Guid playerId, string shopItemId, int purchaseDate, CancellationToken cancellationToken);
    Task AddShopPurchaseHistoryAsync(PlayerShopPurchaseHistory history, CancellationToken cancellationToken);
    Task<PlayerCatState?> GetCatStateAsync(Guid playerId, string catKey, CancellationToken cancellationToken);
    Task<List<PlayerCatState>> GetCatStatesAsync(Guid playerId, CancellationToken cancellationToken);
    Task AddCatStateAsync(PlayerCatState cat, CancellationToken cancellationToken);
    Task<PlayerBuildingState?> GetBuildingStateAsync(Guid playerId, string buildingKey, CancellationToken cancellationToken);
    Task<List<PlayerBuildingState>> GetBuildingStatesAsync(Guid playerId, CancellationToken cancellationToken);
    Task AddBuildingStateAsync(PlayerBuildingState building, CancellationToken cancellationToken);
    Task<List<PlayerDecorState>> GetDecorStatesAsync(Guid playerId, CancellationToken cancellationToken);
    Task<PlayerDecorState?> GetDecorStateAsync(Guid playerId, string decorKey, CancellationToken cancellationToken);
    Task<bool> AddDecorIfMissingAsync(PlayerDecorState decor, CancellationToken cancellationToken);
    Task<PlayerDecorCollectionState?> GetDecorCollectionStateAsync(Guid playerId, CancellationToken cancellationToken);
    Task<bool> ClaimDecorCollectionTierAsync(Guid playerId, int tierBit, DateTimeOffset now, CancellationToken cancellationToken);
    Task<PlayerResearchState?> GetResearchStateAsync(Guid playerId, string researchKey, CancellationToken cancellationToken);
    Task<List<PlayerResearchState>> GetResearchStatesAsync(Guid playerId, CancellationToken cancellationToken);
    Task AddResearchStateAsync(PlayerResearchState research, CancellationToken cancellationToken);
    Task<PlayerLaunchRecord?> GetLaunchRecordAsync(Guid playerId, string clientRequestId, CancellationToken cancellationToken);
    Task AddLaunchRecordAsync(PlayerLaunchRecord record, CancellationToken cancellationToken);
    Task SaveChangesAsync(CancellationToken cancellationToken);
}
