$ErrorActionPreference = "Stop"

$root = Join-Path $PSScriptRoot ".."
$factoryDir = Join-Path $root "FATCATUI/assets/resources/textures/generated/factory"
$outFile = Join-Path $root "FATCATUI/assets/scripts/ui/FactoryPropDataUris.ts"

$assets = [ordered]@{
    office = "prop_office.png"
    roast = "prop_roaster.png"
    tank = "prop_silos.png"
    mill = "prop_mill.png"
    cafe = "prop_cafe.png"
    storage = "prop_storage.png"
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("// Auto-generated by tools/generate-factory-prop-data-uris.ps1.")
$lines.Add("// Keeps small DOM-only factory props available without Cocos preview 404s.")
$lines.Add("export const FactoryPropDataUris: Record<string, string> = {")

foreach ($entry in $assets.GetEnumerator()) {
    $path = Join-Path $factoryDir $entry.Value
    if (!(Test-Path -LiteralPath $path)) {
        throw "Missing generated factory prop: $path"
    }

    $bytes = [System.IO.File]::ReadAllBytes($path)
    $base64 = [System.Convert]::ToBase64String($bytes)
    $lines.Add("    $($entry.Key): `"data:image/png;base64,$base64`",")
}

$lines.Add("};")
$lines.Add("")

[System.IO.File]::WriteAllLines($outFile, $lines, [System.Text.UTF8Encoding]::new($false))
Write-Host "Generated factory prop Data URI registry: $outFile"
