$ErrorActionPreference = "Stop"

$root = Join-Path $PSScriptRoot ".."
$generatedRoot = Join-Path $root "FATCATUI/assets/resources/textures/generated"
$outFile = Join-Path $root "FATCATUI/assets/scripts/ui/DomAssetDataUris.ts"

$relativeAssets = @(
    "factory_cutaway_bg_852_v2.jpg",
    "cat_detail_workshop_bg_640.jpg",
    "backgrounds/friend_factory_visit_bg_640_v1.jpg",
    "building_rooms/room_office_v1.jpg",
    "building_rooms/room_roast_v1.jpg",
    "building_rooms/room_tank_v1.jpg",
    "building_rooms/room_mill_v1.jpg",
    "building_rooms/room_cafe_v1.jpg",
    "building_rooms/room_storage_v1.jpg",
    "factory_appearances/appearance_classic_v1.jpg",
    "factory_appearances/appearance_steam_v1.jpg",
    "factory_appearances/appearance_future_v1.jpg",
    "cats/cat_hero_orange_v2.png",
    "cats/cat_hero_black_v2.png",
    "cats/cat_hero_white_v2.png",
    "cats/cat_hero_calico_v2.png",
    "cats/cat_hero_tuxedo_v2.png",
    "cats/cat_full_orange.png",
    "cats/cat_full_black.png",
    "cats/cat_full_white.png",
    "cats/cat_full_calico.png",
    "cats/cat_full_tuxedo.png",
    "items/icon_coffee_bean.png",
    "items/icon_cat_food.png",
    "items/icon_coin_pack.png",
    "items/icon_diamond.png",
    "items/equip_collar.png",
    "items/equip_cup.png",
    "items/equip_cushion.png",
    "items/equip_locked.png",
    "items/inventory_speed_ticket_v1.png",
    "items/inventory_guard_charm_v1.png",
    "items/inventory_order_voucher_v1.png",
    "items/inventory_cat_food_small_v1.png",
    "items/inventory_cat_food_large_v1.png",
    "items/inventory_super_food_v1.png",
    "items/inventory_factory_voucher_v1.png",
    "items/inventory_accelerator_v1.png",
    "items/inventory_dried_fish_v1.png",
    "items/research_medal_v1.png",
    "items/research_medal_bean_v1.png",
    "items/research_medal_coin_v1.png",
    "items/research_medal_upgrade_v1.png",
    "items/research_node_extract_1_v1.png",
    "items/research_node_roast_1_v1.png",
    "items/research_node_cheap_upgrade_v1.png",
    "items/research_node_extract_2_v1.png",
    "items/research_node_roast_2_v1.png",
    "items/research_node_ferment_2_v1.png",
    "items/research_node_espresso_v1.png",
    "shop/shop_bean_sack_v1.png",
    "shop/shop_cat_food_pouch_v1.png",
    "shop/shop_coin_pouch_v1.png",
    "shop/shop_diamond_chest_v1.png",
    "ui/icon_mail_envelope_v2.png",
    "ui/icon_friend_cat_v2.png",
    "ui/icon_achievement_trophy_v2.png",
    "ui/icon_settings_gear_v2.png",
    "ui/icon_task_clipboard.png",
    "ui/icon_reward_chest.png",
    "ui/icon_launch_rocket.png",
    "ui/nav_factory.png",
    "ui/nav_buildings.png",
    "ui/nav_shop.png",
    "ui/nav_inventory.png",
    "ui/nav_research.png",
    "ui/skill_producer.png",
    "ui/skill_launcher.png",
    "ui/skill_saver.png",
    "ui/skill_support.png"
)

function Get-Mime([string]$path) {
    $ext = [System.IO.Path]::GetExtension($path).ToLowerInvariant()
    if ($ext -eq ".jpg" -or $ext -eq ".jpeg") { return "image/jpeg" }
    return "image/png"
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("// Auto-generated by tools/generate-dom-asset-data-uris.ps1.")
$lines.Add("// DOM overlay bridge for generated assets that Cocos preview will not serve by direct URL.")
$lines.Add("export const DomAssetDataUris: Record<string, string> = {")

foreach ($relative in $relativeAssets) {
    $path = Join-Path $generatedRoot $relative
    if (!(Test-Path -LiteralPath $path)) {
        throw "Missing generated DOM asset: $path"
    }

    $key = "assets/resources/textures/generated/$($relative -replace '\\', '/')"
    $bytes = [System.IO.File]::ReadAllBytes($path)
    $base64 = [System.Convert]::ToBase64String($bytes)
    $mime = Get-Mime $path
    $lines.Add("    `"$key`": `"data:$mime;base64,$base64`",")
}

$lines.Add("};")
$lines.Add("")

[System.IO.File]::WriteAllLines($outFile, $lines, [System.Text.UTF8Encoding]::new($false))
Write-Host "Generated DOM asset Data URI registry: $outFile"
